version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14  # Cambia esta imagen según el entorno
    steps:
      - checkout
      - run:
          name: "Run Hola Mundo Script"
          command: node index.js
workflows:
  version: 2
  test_workflow:
    jobs:
      - build
